### ISSUE TITLE
ACCSの自動生成されるindex.htmlをRubyで祝福したい

### ISSUE THREAD

**Issue by ainjn** [reasonset/purebuilder-simply#3]
# 環境

* Linux Mint 21.2 (kernel 5.15) Cinnamon Edition

* Ruby 3.2.2

* pandoc 3.1.2

# 問題

<code>.pbsimply-bless.rb</code>の<code>PureBuilder::BLESS</code> Procオブジェクトを使ってWebサイトの「パンくずリスト」と「記事の言語切り替えリンク」を作成しようとしていますが，ACCSドキュメントディレクトリ内の<code>index.html</code>だけが祝福されず，サイトのUXが低下することに困っています。

# 機能追加要望

表題の通り，<code>.pbsimply-bless.rb</code>でACCSドキュメントディレクトリ内の<code>index.html</code>を祝福することができるようにしてほしいです。

もし既存の機能だけでACCSインデックスページのfrontmatterを加工することができる場合はこの要望は無視していただいて結構です。

# 優先度

低

**Comment by reasonset** [comment]
ご報告ありがとうございます。

現在、single modeに多数の問題があることを認識しており、developではそれらの問題の一部が修正されています。
しかし、ご指摘の点を含め、依然としてdirectory modeでしか行われない処理も存在し、(生成されるindex.mdの問題を含む)single modeは修正が必要です。

認識はしているのですが、developはこれらの修正と新機能の追加両面ですぐにマージできる状態になく、このままテストしてマージできる状態でもないため、2.1/2.2のリリースはスキップし、もう少し手を加えてから3.0としてリリースします。
ご不便をおかけしますが、今しばらくお待ちください。

**Comment by ainjn** [comment]
ご対応ありがとうございます。

不具合の報告というよりかは個人的な陳情になってしまっているのでこのissueはcloseしておきます。お手を煩わせてしまい申し訳ありません。

**Comment by reasonset** [comment]
現在対応中ですので、openにしておきます。
(その問題自体は、先程上げたdevelopで改善されているはずですが、まだテストしていないため、すべての機能が正しく動作するかはわかりません)
